from pydantic import BaseModel
from datetime import datetime
from typing import Optional

# Base schema with fields shared across all transaction schemas.
class TransactionBase(BaseModel):
    amount: float
    type: str
    category: str
    description: Optional[str] = None
    date: Optional[datetime] = None

# Schema for creating a transaction. Used in POST requests.
# Does not include id as it is generated by the database.
class TransactionCreate(TransactionBase):
    pass

# Schema for updating a transaction. All fields are optional.
# Only provided fields will be updated.
class TransactionUpdate(BaseModel):
    amount: Optional[float] = None
    type: Optional[str] = None
    category: Optional[str] = None
    description: Optional[str] = None
    date: Optional[datetime] = None

# Schema for returning a transaction. Used in GET responses.
# Includes id and date generated by the database.
class TransactionResponse(TransactionBase):
    id: int
    date: datetime

    class Config:
        from_attributes = True